version: '3'
services:
  spring-boot-app:
    image: backend
    ports:
      - "8091:8091"
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://mysql:3306/api_etudiant?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=api_etudiant
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3306:3306'
    volumes:
      - api_etudiant:/var/lib/mysql

volumes:
  api_etudiant:
